name: List Repositories

on:
  schedule:
    - cron: '0 0 * * 0' # Run every Sunday at midnight
  workflow_dispatch:

jobs:
  list-repos:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repositories
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '14'

    - name: List repositories
      run: |
        gh repo list Boomtokn --limit 100
